[package]
name = "arena"
version = "0.1.0"
edition = "2021"

[dependencies]
wait-timeout = "0.2"
clap = { version = "4.5.19", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0.210", features = ["serde_derive"] }
rand = "0.8.5"
rayon = "1.10.0"
crossbeam-channel = "0.5.13"
skillratings = "0.27.1"
cc = "1.1.37"
tempfile = "3.14.0"
current_platform = "0.2.0"
bundler = { path = "../bundler" }
distributed-channel = { path = "/Users/mlomb/distributed-channel" }
inquire = "0.7.5"
yaml-rust2 = "0.9.0"
console = "0.15.8"
env_logger = "0.11.5"
log = "0.4.22"
num_cpus = "1.16.0"
tabled = "0.17.0"
