[package]
name = "battle"
description = "Battlestation CLI for bot contests"
author = "mlomb"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
bundler = { path = "../bundler" }
console = { version = "0.16.3", default-features = false, features = ["ansi-parsing", "std"] }
tempfile = "3.27.0"
build-fs-tree = "0.8.1"
serde = "1.0.228"
distributed-channel = { git = "https://github.com/mlomb/distributed-channel.git" }
num_cpus = "1.17.0"
env_logger = "0.11.10"
log = "0.4.29"
crossbeam-channel = "0.5.15"
