[package]
name = "battle"
description = "Battlestation CLI for bot contests"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
bundler = { path = "../bundler" }
wrapcmd = { path = "../wrapcmd" }
console = { version = "0.16.3", default-features = false, features = ["ansi-parsing", "std"] }
tempfile = "3.27.0"
build-fs-tree = "0.8.1"
serde = { version = "1.0.228", features = ["serde_derive"] }
num_cpus = "1.17.0"
env_logger = "0.11.10"
log = "0.4.29"
tarpc = { version = "0.34", features = ["full", "serde-transport-bincode"] }
futures-util = "0.3.32"
blake3 = "1.8.4"
async-channel = "2.5.0"
anyhow = "1.0.102"
postcard = { version = "1.1.3", features = ["alloc"] }
tokio = { version = "1.51.1", features = ["io-std", "io-util", "macros", "rt-multi-thread", "sync", "net", "signal"] }
rand = "0.10.1"
